const cart = {
  carts: [
    {
      cart_id: '4#2001_miao',
      cart_name: '北京渔阳置业大厦店',
      format: 'SUPERMARKET',
      baskets: [
        {
          id: 2001,
          merchant_name: 'LV专卖店',
          basket_items: [
            {
              id: 33,
              goods: {
                id: 38072,
                merchant_id: 2001,
                sub_site_id: 4,
                name: 'LV 路易威登 CHERIE露跟高跟鞋 1A8UMN',
                weight: '600.0000',
                status: 'ENABLE',
                category_id: 14030,
                product_id: 30012,
                brand_id: 22007,
                style_id: 30028,
                virtual_category_id: 0,
                price: {
                  price_value: '7400.00',
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '7400.0000'
                },
                shelf_status: 1,
                available_stock: 71,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-04 12:21:21',
              quantity: 9,
              execute_price: '7400.00',
              execute_point_price: 0,
              deal_amount: '66600.00',
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '600.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/7d9d98d582eac0ae7460b753254cad96_300x300.png',
              style_name: '尺寸:39 ',
              style_name_en: ': ',
              group_buying_sign: null
            },
            {
              id: 39,
              goods: {
                id: 38068,
                merchant_id: 2001,
                sub_site_id: 4,
                name: 'LV 路易威登 CHERIE露跟高跟鞋 1A8UMN',
                weight: '600.0000',
                status: 'ENABLE',
                category_id: 14030,
                product_id: 30012,
                brand_id: 22007,
                style_id: 30024,
                virtual_category_id: 0,
                price: {
                  price_value: '7400.00',
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '7400.0000'
                },
                shelf_status: 1,
                available_stock: 71,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 11:43:58',
              quantity: 1,
              execute_price: '7400.00',
              execute_point_price: 0,
              deal_amount: '7400.00',
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '600.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/7d9d98d582eac0ae7460b753254cad96_300x300.png',
              style_name: '尺寸:35 ',
              style_name_en: ': ',
              group_buying_sign: null
            },
            {
              id: 40,
              goods: {
                id: 40065,
                merchant_id: 2001,
                sub_site_id: 4,
                name: 'LV 路易威登 CHERIE露跟高跟鞋 1A86GF',
                weight: '600.0000',
                status: 'ENABLE',
                category_id: 14030,
                product_id: 32011,
                brand_id: 22007,
                style_id: 32023,
                virtual_category_id: 0,
                price: {
                  price_value: '6700.00',
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '6700.0000'
                },
                shelf_status: 1,
                available_stock: 70,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 16:28:12',
              quantity: 7,
              execute_price: '6700.00',
              execute_point_price: 0,
              deal_amount: '46900.00',
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '600.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/671cbb3bc7fba818815f865da8281005_300x300.png',
              style_name: '尺寸:36 ',
              style_name_en: ': ',
              group_buying_sign: null
            },
            {
              id: 42,
              goods: {
                id: 38070,
                merchant_id: 2001,
                sub_site_id: 4,
                name: 'LV 路易威登 CHERIE露跟高跟鞋 1A8UMN',
                weight: '600.0000',
                status: 'ENABLE',
                category_id: 14030,
                product_id: 30012,
                brand_id: 22007,
                style_id: 30026,
                virtual_category_id: 0,
                price: {
                  price_value: '7400.00',
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '7400.0000'
                },
                shelf_status: 1,
                available_stock: 71,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 16:28:56',
              quantity: 1,
              execute_price: '7400.00',
              execute_point_price: 0,
              deal_amount: '7400.00',
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '600.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/7d9d98d582eac0ae7460b753254cad96_300x300.png',
              style_name: '尺寸:37 ',
              style_name_en: ': ',
              group_buying_sign: null
            },
            {
              id: 43,
              goods: {
                id: 38071,
                merchant_id: 2001,
                sub_site_id: 4,
                name: 'LV 路易威登 CHERIE露跟高跟鞋 1A8UMN',
                weight: '600.0000',
                status: 'ENABLE',
                category_id: 14030,
                product_id: 30012,
                brand_id: 22007,
                style_id: 30027,
                virtual_category_id: 0,
                price: {
                  price_value: '7400.00',
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '7400.0000'
                },
                shelf_status: 1,
                available_stock: 71,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 16:29:06',
              quantity: 1,
              execute_price: '7400.00',
              execute_point_price: 0,
              deal_amount: '7400.00',
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '600.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/7d9d98d582eac0ae7460b753254cad96_300x300.png',
              style_name: '尺寸:38 ',
              style_name_en: ': ',
              group_buying_sign: null
            },
            {
              id: 45,
              goods: {
                id: 40087,
                merchant_id: 2001,
                sub_site_id: 4,
                name: 'LV 路易威登 URBAN TWIST 高跟鞋 1A7RZY',
                weight: '600.0000',
                status: 'ENABLE',
                category_id: 14030,
                product_id: 32014,
                brand_id: 22007,
                style_id: 32045,
                virtual_category_id: 0,
                price: {
                  price_value: '8200.00',
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '8200.0000'
                },
                shelf_status: 1,
                available_stock: 55,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 16:31:35',
              quantity: 1,
              execute_price: '8200.00',
              execute_point_price: 0,
              deal_amount: '8200.00',
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '600.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/5203ee22c056a21ef4133ae7b9d8053a_300x300.png',
              style_name: '尺寸:37 ',
              style_name_en: ': ',
              group_buying_sign: null
            },
            {
              id: 47,
              goods: {
                id: 38069,
                merchant_id: 2001,
                sub_site_id: 4,
                name: 'LV 路易威登 CHERIE露跟高跟鞋 1A8UMN',
                weight: '600.0000',
                status: 'ENABLE',
                category_id: 14030,
                product_id: 30012,
                brand_id: 22007,
                style_id: 30025,
                virtual_category_id: 0,
                price: {
                  price_value: '7400.00',
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '7400.0000'
                },
                shelf_status: 1,
                available_stock: 17,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 17:35:27',
              quantity: 1,
              execute_price: '7400.00',
              execute_point_price: 0,
              deal_amount: '7400.00',
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '600.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/7d9d98d582eac0ae7460b753254cad96_300x300.png',
              style_name: '尺寸:36 ',
              style_name_en: ': ',
              group_buying_sign: null
            }
          ],
          rewards: [],
          promotions: null,
          cart_time_limits: [],
          total_point_amount: 0,
          total_amount: 0,
          total_cart_amount_discount: 0,
          total_cart_freight_amount_discount: 0,
          total_checkout_amount_discount: 0,
          total_coupon_amount_discount: 0,
          total_checkout_freight_discount: 0,
          total_coupon_freight_discount: 0,
          total_freight_discount: 0,
          total_amount_discount: 0,
          total_weight: 0,
          valid_total_quantity: 0,
          short_rewards: null,
          has_available_coupon: false,
          activity_id: null
        },
        {
          id: 0,
          merchant_name: '自营',
          basket_items: [
            {
              id: 12,
              goods: {
                id: 52063,
                merchant_id: 0,
                sub_site_id: 4,
                name: 'GIVENCHY纪梵希香榭唇膏定制版套装 精品唇膏定制壳',
                weight: '10.0000',
                status: 'ENABLE',
                category_id: 14011,
                product_id: 44011,
                brand_id: 30007,
                style_id: 44021,
                virtual_category_id: 0,
                price: {
                  price_value: 0.01,
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '0.0100'
                },
                shelf_status: 1,
                available_stock: 1000,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 11:43:50',
              quantity: 1,
              execute_price: 0.01,
              execute_point_price: 0,
              deal_amount: 0.01,
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '10.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/0b431c152b8aebba60131956c47ea74a_300x300.jpg',
              style_name: '型号:基础款 ',
              style_name_en: 'Type: ',
              group_buying_sign: null
            },
            {
              id: 14,
              goods: {
                id: 52064,
                merchant_id: 0,
                sub_site_id: 4,
                name: 'GIVENCHY纪梵希香榭唇膏定制版套装 精品唇膏定制壳',
                weight: '10.0000',
                status: 'ENABLE',
                category_id: 14011,
                product_id: 44011,
                brand_id: 30007,
                style_id: 44022,
                virtual_category_id: 0,
                price: {
                  price_value: 0.01,
                  type: 'SALE_PRICE',
                  point_price: 0,
                  original_price: '0.0100'
                },
                shelf_status: 1,
                available_stock: 1000,
                goods_tags: [],
                minimum_order_quantity: null,
                unavailable_reason: null,
                unavailable: false
              },
              addtime: '2021-06-07 17:34:31',
              quantity: 1,
              execute_price: 0.01,
              execute_point_price: 0,
              deal_amount: 0.01,
              deal_point_amount: 0,
              after_folding_price: 0,
              total_freight_discount: 0,
              total_amount_discount: 0,
              single_amount_discount: 0,
              multi_amount_discount: 0,
              rewards: null,
              status: 1,
              invalid_message: '',
              weight: '10.0000',
              select: false,
              thumb_url:
                'https://comall-magic-dev.oss-cn-beijing.aliyuncs.com/assets/upload/miao/product/0b431c152b8aebba60131956c47ea74a_300x300.jpg',
              style_name: '型号:A ',
              style_name_en: 'Type:A ',
              group_buying_sign: null
            }
          ],
          rewards: [],
          promotions: null,
          cart_time_limits: [],
          total_point_amount: 0,
          total_amount: 0,
          total_cart_amount_discount: 0,
          total_cart_freight_amount_discount: 0,
          total_checkout_amount_discount: 0,
          total_coupon_amount_discount: 0,
          total_checkout_freight_discount: 0,
          total_coupon_freight_discount: 0,
          total_freight_discount: 0,
          total_amount_discount: 0,
          total_weight: 0,
          valid_total_quantity: 0,
          short_rewards: null,
          has_available_coupon: false,
          activity_id: null
        }
      ],
      total_amount: 0,
      payable_amount: 0,
      total_point_amount: 0,
      total_amount_discount: 0,
      total_cart_amount_discount: 0,
      total_checkout_amount_discount: 0,
      total_coupon_amount_discount: 0,
      total_checkout_freight_discount: 0,
      total_coupon_freight_discount: 0,
      total_freight_discount: 0,
      total_weight: 0,
      total_quantity: 23,
      select_total_quantity: 0,
      valid_total_quantity: 23
    }
  ],
  total_amount: 0,
  payable_amount: 0,
  total_point_amount: 0,
  total_amount_discount: 0,
  total_weight: 0,
  total_quantity: 23,
  select_total_quantity: 0,
  valid_total_quantity: 23
};
